FROM php:7.3

RUN apt-get clean
RUN apt-get update
RUN apt-get install -y libzip-dev zip && docker-php-ext-install zip
RUN pecl install apcu-5.1.18 && docker-php-ext-enable apcu

RUN mkdir /app
WORKDIR /app
COPY ./app/ /app/

RUN composer install
ENTRYPOINT ["php", "-S", "0.0.0.0:8082", "index.php"]

EXPOSE 8082
