scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
        labels:
          env: local
          region: us-east-1

  - job_name: 'codely'
    scrape_interval: 5s
    static_configs:
      - targets: ['app:8081']
